spring:
  main:
    banner-mode: "off"
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: example
    driver-class-name: org.postgresql.Driver
  batch:
    jdbc:
      initialize-schema: always
logging:
  level:
    root: WARN
    "de.mem89.*": INFO
    "de.mem89.imdb.dataset_importer.writer.*": DEBUG

app:
  datasets:
    titleBasics:
      filename: title.basics.tsv.gz
      mapperBean: titleBasicsMapper
    nameBasics:
      filename: name.basics.tsv.gz
      mapperBean: nameBasicsMapper
  chunk_size: 32768
